FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY r.in ./
RUN pip install --no-cache-dir -r r.in

COPY . .

EXPOSE 1234

CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "1234", "--reload"]