FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install fastapi uvicorn omegaconf psycopg2-binary dotenv

EXPOSE 1234

CMD ["python", "main.py", "--host", "0.0.0.0", "--port", "1234"]