networks:
  highly_accurate_network:
    driver: bridge
    ipam:
      config:
      - subnet: 8.8.0.0/16
      driver: default
services:
  artery:
    build:
      context: C:\Users\USER\Documents\GitHub\cavise\scenario-manager\ruchki
      dockerfile: artery/Dockerfile
    command:
    - sh
    - -c
    - sleep infinity
    container_name: artery
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            driver: nvidia
    environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=${XAUTHORITY}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD
      - ping
      - -c
      - '1'
      - artery
      timeout: 10s
    networks:
      highly_accurate_network:
        ipv4_address: 8.8.0.12
    privileged: true
    volumes:
    - ../simdata:/cavise/simdata
    - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ${XAUTHORITY}:${XAUTHORITY}
  carla:
    build:
      context: C:\Users\USER\Documents\GitHub\cavise\scenario-manager\ruchki
      dockerfile: carla/Dockerfile
    command:
    - sh
    - -c
    - sleep infinity
    container_name: carla
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            driver: nvidia
    environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=${XAUTHORITY}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD
      - ping
      - -c
      - '1'
      - carla
      timeout: 10s
    networks:
      highly_accurate_network:
        ipv4_address: 8.8.0.11
    privileged: true
    volumes:
    - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ${XAUTHORITY}:${XAUTHORITY}
  opencda:
    build:
      context: C:\Users\USER\Documents\GitHub\cavise\scenario-manager\ruchki
      dockerfile: opencda/Dockerfile
    command:
    - sh
    - -c
    - sleep infinity
    container_name: opencda
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            driver: nvidia
    environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=${XAUTHORITY}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD
      - ping
      - -c
      - '1'
      - opencda
      timeout: 10s
    networks:
      highly_accurate_network:
        ipv4_address: 8.8.0.10
    privileged: true
    volumes:
    - ../cavise/messages:/cavise/cavise/messages
    - ../simdata:/cavise/simdata
    - ../opencda:/cavise/opencda
    - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ${XAUTHORITY}:${XAUTHORITY}
  redis:
    build:
      context: C:\Users\USER\Documents\GitHub\cavise\scenario-manager\ruchki
      dockerfile: redis/Dockerfile
    command:
    - sh
    - -c
    - sleep infinity
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            driver: nvidia
    environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=${XAUTHORITY}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD
      - ping
      - -c
      - '1'
      - redis
      timeout: 10s
    image: redis:7.4.1
    networks:
      highly_accurate_network:
        ipv4_address: 8.8.0.9
    ports:
    - 6369:6379
    volumes:
    - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ${XAUTHORITY}:${XAUTHORITY}
  scenario-manager:
    build:
      context: C:\Users\USER\Documents\GitHub\cavise\scenario-manager\ruchki
      dockerfile: scenario-manager/Dockerfile
    command:
    - sh
    - -c
    - sleep infinity
    container_name: scenario-manager
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            driver: nvidia
    environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=${XAUTHORITY}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD
      - ping
      - -c
      - '1'
      - scenario-manager
      timeout: 10s
    image: sc-mn
    networks:
      highly_accurate_network:
        ipv4_address: 8.8.0.8
    ports:
    - 8999:8999
    volumes:
    - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ${XAUTHORITY}:${XAUTHORITY}
