import { mergeSimConfigWithDefaults, type SimulationConfig } from '../types/configGeneratorsTypes';
import type { Car, Point, RSU } from '../../../../store/types/useEditorStoreTypes';

const CAM_POSITIONS = [
  '[2.5, 0, 1.0, 0]',
  '[0.0, 0.3, 1.8, 100]',
  '[0.0, -0.3, 1.8, -100]',
  '[-2.0, 0.0, 1.5, 180]',
];

export function generateOpenCDAConfig(
  config: SimulationConfig,
  cars: Car[],
  rsus: RSU[],
  points: Point[],
): string {
  const cfg   = mergeSimConfigWithDefaults(config);
  const oc    = cfg.opencda;
  const carla = cfg.carla;
  const ls    = oc.lidar_sim;
  const lp    = oc.local_planner;
  const gn    = oc.gnss_noise;
  const bgR   = oc.bg_spawn_range;
  const lines: string[] = [];

  lines.push(`description: |-`);
  lines.push(`  OpenCDA scenario generated by ScenarioManager`);
  lines.push(`  Town: ${carla.map} | Vehicles: ${cars.length} | RSUs: ${rsus.length}`);
  lines.push('');

  lines.push('world:');
  lines.push(`  town: ${carla.map}`);
  lines.push(`  weather: ${carla.weather_preset}`);
  lines.push(`  fixed_delta_seconds: ${carla.fixed_delta_seconds}`);
  lines.push(`  simulation_time: ${cfg.sim_duration}`);
  lines.push(`  sync_mode: ${carla.synchronous_mode}`);
  lines.push(`  client_port: ${carla.client_port}`);
  lines.push(`  seed: ${carla.seed}`);
  lines.push('');

  lines.push('blueprint:');
  lines.push(`  use_multi_class_bp: ${oc.use_multi_class_bp}`);
  lines.push(`  bp_meta_path: "${oc.bp_meta_path}"`);
  lines.push('  bp_class_sample_prob:');
  lines.push(`    car: ${oc.bp_class_sample_prob.car}`);
  lines.push(`    truck: ${oc.bp_class_sample_prob.truck}`);
  lines.push(`    bus: ${oc.bp_class_sample_prob.bus}`);
  lines.push(`    bicycle: ${oc.bp_class_sample_prob.bicycle}`);
  lines.push(`    motorcycle: ${oc.bp_class_sample_prob.motorcycle}`);
  lines.push('');

  lines.push('rsu_base:');
  lines.push('  sensing:');
  lines.push('    perception:');
  lines.push(`      activate: ${oc.rsu_perception_activate}`);
  if (oc.rsu_cam_num > 0) {
    lines.push('      camera:');
    lines.push(`        visualize: ${oc.rsu_camera_visualize}`);
    lines.push(`        num: ${oc.rsu_cam_num}`);
    lines.push('        positions:');
    for (let i = 0; i < Math.min(oc.rsu_cam_num, 4); i++) {
      lines.push(`          - ${CAM_POSITIONS[i]}`);
    }
  } else {
    lines.push('      camera:');
    lines.push(`        visualize: ${oc.rsu_camera_visualize}`);
    lines.push('        num: 0');
  }
  lines.push('      lidar:');
  lines.push(`        visualize: ${oc.lidar_visualize}`);
  lines.push(`        channels: ${oc.rsu_lidar_channels}`);
  lines.push(`        range: ${oc.rsu_lidar_range}`);
  lines.push(`        points_per_second: ${oc.lidar_points_per_second}`);
  lines.push(`        rotation_frequency: ${oc.lidar_rotation_frequency}`);
  lines.push(`        upper_fov: ${oc.lidar_upper_fov}`);
  lines.push(`        lower_fov: ${oc.lidar_lower_fov}`);
  lines.push(`        dropoff_general_rate: ${ls.dropoff_general_rate}`);
  lines.push(`        dropoff_intensity_limit: ${ls.dropoff_intensity_limit}`);
  lines.push(`        dropoff_zero_intensity: ${ls.dropoff_zero_intensity}`);
  lines.push(`        noise_stddev: ${ls.noise_stddev}`);
  lines.push('    localization:');
  lines.push(`      activate: ${oc.localization_activate}`);
  if (oc.localization_activate) {
    lines.push('      dt: ${world.fixed_delta_seconds}');
    lines.push('      gnss:');
    lines.push(`        noise_alt_stddev: ${gn.alt_stddev}`);
    lines.push(`        noise_lat_stddev: ${gn.lat_stddev}`);
    lines.push(`        noise_lon_stddev: ${gn.lon_stddev}`);
  }
  lines.push('');

  lines.push('vehicle_base:');
  lines.push('  sensing:');
  lines.push('    perception:');
  lines.push(`      activate: ${oc.perception_activate}`);
  lines.push('      camera:');
  lines.push(`        visualize: ${oc.vehicle_camera_visualize}`);
  lines.push(`        num: ${oc.vehicle_cam_num}`);
  if (oc.vehicle_cam_num > 0) {
    lines.push('        positions:');
    for (let i = 0; i < Math.min(oc.vehicle_cam_num, 4); i++) {
      lines.push(`          - ${CAM_POSITIONS[i]}`);
    }
  }
  lines.push('      lidar:');
  lines.push(`        visualize: ${oc.lidar_visualize}`);
  lines.push(`        channels: ${oc.lidar_channels}`);
  lines.push(`        range: ${oc.lidar_range}`);
  lines.push(`        points_per_second: ${oc.lidar_points_per_second}`);
  lines.push(`        rotation_frequency: ${oc.lidar_rotation_frequency}`);
  lines.push(`        upper_fov: ${oc.lidar_upper_fov}`);
  lines.push(`        lower_fov: ${oc.lidar_lower_fov}`);
  lines.push(`        dropoff_general_rate: ${ls.dropoff_general_rate}`);
  lines.push(`        dropoff_intensity_limit: ${ls.dropoff_intensity_limit}`);
  lines.push(`        dropoff_zero_intensity: ${ls.dropoff_zero_intensity}`);
  lines.push(`        noise_stddev: ${ls.noise_stddev}`);
  lines.push('    localization:');
  lines.push(`      activate: ${oc.localization_activate}`);
  lines.push('      debug_helper:');
  lines.push(`        show_animation: ${oc.vehicle_localization_debug_animation}`);
  lines.push('  behavior:');
  lines.push(`    max_speed: ${oc.max_speed}`);
  lines.push(`    tailgate_speed: ${oc.tailgate_speed}`);
  lines.push(`    speed_lim_dist: ${oc.speed_lim_dist}`);
  lines.push(`    speed_decrease: ${oc.speed_decrease}`);
  lines.push(`    safety_time: ${oc.safety_time}`);
  lines.push(`    emergency_param: ${oc.emergency_param}`);
  lines.push(`    ignore_traffic_light: ${oc.ignore_traffic_light}`);
  lines.push(`    overtake_allowed: ${oc.overtake_allowed}`);
  lines.push(`    collision_time_ahead: ${oc.collision_time_ahead}`);
  lines.push(`    overtake_counter_recover: ${oc.overtake_counter_recover}`);
  lines.push(`    sample_resolution: ${oc.sample_resolution}`);
  lines.push('    local_planner:');
  lines.push(`      buffer_size: ${lp.buffer_size}`);
  lines.push(`      trajectory_update_freq: ${lp.trajectory_update_freq}`);
  lines.push(`      waypoint_update_freq: ${lp.waypoint_update_freq}`);
  lines.push(`      min_dist: ${lp.min_dist}`);
  lines.push(`      trajectory_dt: ${lp.trajectory_dt}`);
  lines.push(`      debug: ${lp.debug}`);
  lines.push(`      debug_trajectory: ${lp.debug_trajectory}`);
  lines.push('');

  lines.push('sumo:');
  lines.push(`  port: ${oc.sumo_port}`);
  lines.push(`  host: ${oc.sumo_host}`);
  lines.push(`  gui: ${oc.sumo_gui}`);
  lines.push(`  client_order: ${oc.sumo_client_order}`);
  lines.push(`  step_length: \${world.fixed_delta_seconds}`);
  lines.push('');

  if (oc.enable_background_traffic) {
    lines.push('carla_traffic_manager:');
    lines.push(`  global_speed_perc: ${oc.global_speed_perc}`);
    lines.push(`  global_distance: ${oc.bg_global_distance}`);
    lines.push(`  auto_lane_change: ${oc.auto_lane_change}`);
    lines.push(`  set_osm_mode: ${oc.bg_set_osm_mode}`);
    lines.push(`  random: ${oc.bg_traffic_random}`);
    lines.push(`  ignore_lights_percentage: ${oc.ignore_lights_percentage}`);
    lines.push(`  ignore_signs_percentage: ${oc.bg_ignore_signs_percentage}`);
    lines.push(`  ignore_walkers_percentage: ${oc.bg_ignore_walkers_percentage}`);
    lines.push('  vehicle_list: ~');
    lines.push('  range:');
    lines.push(`    - [${bgR.x_min}, ${bgR.x_max}, ${bgR.y_min}, ${bgR.y_max}, ${bgR.z_min}, ${bgR.z_max}, ${oc.bg_vehicle_num}]`);
    lines.push('');
  }

  lines.push('scenario:');

  if (rsus.length > 0) {
    lines.push('  rsu_list:');
    rsus.forEach((rsu, i) => {
      lines.push(`    - name: rsu${i + 1}`);
      lines.push(`      spawn_position: [${rsu.x.toFixed(2)}, ${rsu.y.toFixed(2)}, ${rsu.z.toFixed(2)}, 0, 0, 0]`);
      lines.push(`      id: ${i + 1}`);
      lines.push(`      # tx_power: ${rsu.tx_power} | frequency: ${rsu.frequency} | range: ${rsu.range} | protocol: ${rsu.protocol}`);
    });
  } else {
    lines.push('  rsu_list:');
  }

  if (cars.length > 0) {
    lines.push('  single_cav_list:');
    cars.forEach((car, i) => {
      const yawDeg    = car.rotation ? (car.rotation * 57.2958).toFixed(1) : '0.0';
      const carPoints = car.id ? points.filter(p => p.carId === car.id) : [];
      lines.push(`    - name: cav${i + 1}`);
      lines.push(`      spawn_position: [${car.x.toFixed(2)}, ${car.y.toFixed(2)}, ${car.z.toFixed(2)}, 0, ${yawDeg}, 0]`);
      if (carPoints.length > 0) {
        const dest = carPoints[carPoints.length - 1];
        lines.push(`      destination: [${dest.x.toFixed(2)}, ${dest.y.toFixed(2)}, ${dest.z.toFixed(2)}]`);
      }
      lines.push(`      id: ${i + 1}`);
      if (car.opencda_max_speed != null) {
        lines.push('      behavior:');
        lines.push(`        max_speed: ${car.opencda_max_speed}`);
      }
      lines.push(`      # model: ${car.model || 'vehicle.tesla.model3'} | speed: ${car.speed ?? oc.max_speed} km/h`);
    });
  } else {
    lines.push('  single_cav_list:');
  }

  return lines.join('\n');
}
