export const MAX_BUILDING_LOAD_ATTEMPTS = 10;
export const BUILDING_LOAD_RETRY_INTERVAL_MS = 300;
export const BUILDING_LOAD_TIMEOUT_MS =
  MAX_BUILDING_LOAD_ATTEMPTS * BUILDING_LOAD_RETRY_INTERVAL_MS;
