import {
  defaultOpenCDAController,
  defaultOpenCDACoopPerceptionViz,
  defaultOpenCDAMapManager,
  defaultOpenCDAMetrics,
  defaultOpenCDAPlatoonBase,
  defaultOpenCDASafetyManager,
  defaultOpenCDAVehicleBehaviorServices,
} from './opencdaFieldDefaults';
import type { SimulationConfig } from '../types/configGeneratorsTypes';

export const defaultSimConfig: SimulationConfig = {
  sim_duration: 100,
  attacks: [],
  omnet: {
    tx_power: 20,
    bitrate: 6,
    beaconing_interval: 100,
    max_interf_dist: 2600,
    protocol: 'ITS-G5',
  },
  artery: {
    middleware_update_interval: 100,
    datetime: '2024-06-01 12:00:00',
    sumo_config: 'scenario.sumocfg',
    sumo_step_length: 0.1,
    sumo_seed: 42,
    cam_interval_min: 100,
    cam_interval_max: 1000,
    denm_enabled: true,
    cp_service_enabled: false,
    rsu_cam_enabled: true,
    rsu_denm_enabled: true,
  },
  sionna: {
    carrier_frequency: 5.9e9,
    max_depth: 5,
    num_samples: 1e6,
    los: true,
    reflection: true,
    diffraction: true,
    scattering: false,
  },
  carla: {
    map: 'Town03',
    weather_preset: 'ClearNoon',
    weather_override: {},
    client_port: 2000,
    seed: 42,
    num_vehicles: 50,
    num_pedestrians: 20,
    fixed_delta_seconds: 0.05,
    traffic_manager_port: 8001,
    synchronous_mode: true,
    sensors: { camera: true, lidar: true, radar: false, gnss: true, imu: true },
    lidar_channels: 32,
    lidar_range: 50,
    camera_fov: 90,
  },
  opencda: {
    use_multi_class_bp: false,
    bp_meta_path: 'opencda/assets/blueprint_meta/bbx_stats_0912.json',
    bp_class_sample_prob: {
      car: 0.5,
      truck: 0.1,
      bus: 0.1,
      bicycle: 0.1,
      motorcycle: 0.1,
    },
    sumo_port: 3000,
    sumo_host: 'sumo',
    sumo_gui: true,
    sumo_client_order: 1,
    max_speed: 45,
    tailgate_speed: 55,
    speed_lim_dist: 5,
    speed_decrease: 15,
    safety_time: 4,
    emergency_param: 0.4,
    ignore_traffic_light: true,
    overtake_allowed: true,
    collision_time_ahead: 1.5,
    sample_resolution: 2,
    overtake_counter_recover: 35,
    static_obstacle_avoidance_enabled: false,
    lidar_channels: 32,
    lidar_range: 50,
    lidar_points_per_second: 100_000,
    lidar_rotation_frequency: 20,
    lidar_upper_fov: 10,
    lidar_lower_fov: -30,
    lidar_visualize: false,
    vehicle_cam_num: 1,
    perception_activate: false,
    localization_activate: true,
    localization_navigation_source: 'estimated',
    enable_background_traffic: false,
    global_speed_perc: -100,
    auto_lane_change: false,
    ignore_lights_percentage: 0,
    bg_vehicle_num: 15,
    bg_global_distance: 5,
    bg_set_osm_mode: true,
    bg_ignore_signs_percentage: 0,
    bg_ignore_walkers_percentage: 0,
    rsu_perception_activate: false,
    rsu_lidar_channels: 32,
    rsu_lidar_range: 50,
    rsu_cam_num: 1,
    rsu_camera_visualize: 0,
    vehicle_camera_visualize: 0,
    lidar_sim: {
      dropoff_general_rate: 0,
      dropoff_intensity_limit: 1,
      dropoff_zero_intensity: 0,
      noise_stddev: 0,
    },
    local_planner: {
      buffer_size: 12,
      trajectory_update_freq: 15,
      waypoint_update_freq: 9,
      min_dist: 3,
      trajectory_dt: 0.2,
      debug: true,
      debug_trajectory: true,
    },
    gnss_noise: {
      alt_stddev: 0.001,
      lat_stddev: 1e-6,
      lon_stddev: 1e-6,
      heading_direction_stddev: 0.1,
      speed_stddev: 0.2,
    },
    vehicle_localization_debug_animation: false,
    localization_debug_x_scale: 1,
    localization_debug_y_scale: 100,
    vehicle_base_color: undefined,
    v2x_enabled: true,
    v2x_communication_range: 35,
    v2x_position_source: 'estimated',
    export_profile: 'standard',
    export_attacks: true,
    export_platoon_base: false,
    export_metrics: false,
    export_coop_perception: false,
    export_vehicle_behavior_services: false,
    export_world_client_host: false,
    world_client_host: 'localhost',
    ignore_vehicles_percentage: 0,
    random_left_lanechange_percentage: 0,
    random_right_lanechange_percentage: 0,
    map_manager: { ...defaultOpenCDAMapManager },
    safety_manager: { ...defaultOpenCDASafetyManager },
    controller_pid: { ...defaultOpenCDAController },
    platoon_base: { ...defaultOpenCDAPlatoonBase },
    metrics: { ...defaultOpenCDAMetrics },
    vehicle_behavior_services: { ...defaultOpenCDAVehicleBehaviorServices },
    coop_perception: { ...defaultOpenCDACoopPerceptionViz },
    bg_traffic_random: false,
    bg_spawn_range: {
      x_min: 0,
      x_max: 500,
      y_min: 0,
      y_max: 500,
      x_step: 3.5,
      y_step: 15,
    },
  },
  sumo: {
    scenario_name: 'scenario',
    full_output: false,
    vtypes: [
      {
        id: 'vType_0',
        minGap: 2,
        tau: 0.4,
        vClass: 'passenger',
        carFollowModel: 'IDMM',
        speedFactor: 'normc(1.00,0.00)',
      },
    ],
  },
  capi: {
    address: 'tcp://*:7777',
    client_id: 1,
    traci_hostname: 'sumo',
    traci_port: 3000,
    network: 'artery.inet.World',
    cmdenv_express_mode: false,
    cmdenv_output_file: '.cmdenv-log',
    scalar_recording: false,
    vector_recording: false,
    capi_log_level: 'debug',
    middleware_update_interval: 0.1,
    datetime: '2013-06-01 12:35:00',
    carrier_frequency: '5.9 GHz',
    tx_power: '200 mW',
    channel_number: 180,
    ca_service_enabled: true,
    ca_service_port: 2001,
    cosim_service_enabled: true,
    cosim_service_port: 2002,
    cosim_filter_pattern: '(cav|rsu)-.*',
    extra_configs: [
      {
        name: 'gemv2',
        path_loss_type: 'Gemv2',
        small_scale_variations: false,
        visualization: true,
      },
    ],
  },
  mpc: {
    NX: 4,
    NU: 2,
    T: 3,
    T_aug: 30,
    dist_stop: 1.5,
    speed_stop: 0.5,
    time_max: 500,
    iter_max: 5,
    target_speed: 10,
    n_ind: 10,
    dt: 0.1,
    d_dist: 1,
    du_res: 0.25,
    Qf: [5, 5, 0, 20],
    R: [0.01, 5.8],
    Rd: [0.01, 10.1],
    RF: 3.3,
    RB: 0.8,
    W: 2.4,
    wd_ratio: 0.7,
    WB: 2.5,
    TR: 0.44,
    TW: 0.7,
    steer_deg: 60,
    steer_change_deg: 30,
    speed_max_kph: 55,
    speed_min_kph: -20,
    acceleration_max: 1,
  },
};
