name: Scenario Manager Tests

on:
  push:
  pull_request:

jobs:
  frontend:
    uses: CAVISE/pipelines/.github/workflows/node-yarn-vitest.yml@main
    with:
      node-version: "22"
      working-directory: frontend
      cache-dependency-path: frontend/yarn.lock
      coverage: true

  backend:
    uses: CAVISE/pipelines/.github/workflows/python-pytest.yml@main
    with:
      python-versions: '["3.12"]'
      cache-dependency-path: requirements-dev.txt
      requirements-file: requirements-dev.txt
      pytest-test-path: tests/backend
      coverage: true
      coverage-paths: '["app", "simulation/app"]'
